# Generated by Django 5.1.4 on 2025-01-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('float_me_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='permissions',
            field=models.JSONField(default=dict),
        ),
    ]
