# Generated by Django 5.1.4 on 2025-01-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('float_me_app', '0004_admin_created_at_admin_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='sub_token',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
