# Generated by Django 5.1.4 on 2025-01-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('float_me_app', '0007_alter_subscription_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('pending', 'Pending'), ('matured', 'Matured')], default='active', max_length=20),
        ),
    ]
