# Generated by Django 5.1.4 on 2025-02-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('float_me_app', '0008_alter_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payout_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
